keycloak:
  # the name of the realm, required
  realm: xdevops
  # the client-id of the application, required
  resource: springboot-keycloak-demo
  # the base URL of the Keycloak server, required
  auth-server-url: http://localhost:8180/auth
  # establishes if communications with the Keycloak server must happen over HTTPS
  # set to external, meaning that it's only needed for external requests (default value)
  # In production, instead, we should set it to all. Optional
  ssl-required: external
  # prevents the application from sending credentials to the Keycloak server (false is the default value)
  # set it to true whenever we use public clients instead of confidential
  # when access type in keycloak is `confidential` must set `public-client: false`
  public-client: false
  # client secret: client id and secret
  # https://www.keycloak.org/docs/latest/securing_apps/index.html#_client_authentication_adapter
  credentials:
    secret: "1804cd92-b659-4d0e-9bac-c25aac2c9981"
  # the attribute with which to populate the UserPrincipal name
  principal-attribute: preferred_username



